name: Continous integration
on:
  pull_request:
    types: [ opened, reopened ]
  push:
    branches-ignore:
      - master
jobs:
  code_checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: composer install
      - name: Test code style
        run: vendor/bin/ecs
      - name: Static analysis
        run: vendor/bin/phpstan
  commitlint:
    name: commit-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ../../commitlint.config.js
